server:
  port: 8803
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 3000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:  #模板引擎
    cache: false  #模板缓存
    charset: UTF-8  #模板编码
    template-loader-path: classpath:/templates  #设置ftl文件根路径
    request-context-attribute: request  #request-context为request
    suffix: .ftl  #文件后缀
    prefix: /view  #文件前缀
file:
  download-path: D:\\myFile\\download\\
  upload-path: D:\\myFile\\upload\\
  compress-path: D:\\myFile\\compress\\
  decompress-path: D:\\myFile\\decompress\\
  file-type-array: .png,.jpg,.jpeg,.txt,.zip,.rar,.pdf,.xml,xls
  max-file-size: 8192

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  okhttp:
    enabled: true
# 短信验证码
sms:
  app-code: c2e7b42bbda342fd854a3e3c6a73273f
  template-id: JM1000372
