spring:
  datasource:
    url: jdbc:mysql://192.168.146.27:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  elasticsearch:
    rest:
      uris: http://192.168.146.27:9200
management:
  health:
    elasticsearch:
      response-timeout: 1000ms #加大健康检查超时时间
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: logstash
