server:
  port: 8801
spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      time-between-eviction-runs-millis: 600000  #Druid默认每60s运行一次空闲连接回收器，所以超过60s没有使用的连接会被释放，并打印 WARN 日志 discard long time none received connection。出现这个警告可能是业务中执行 SQL 操作的间隔时间比较长。解决办法是，将连接空闲时间 timeBetweenEvictionRunsMillis 设置大一些
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq: #rabbitmq相关配置
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时
aliyun:
  oss:
    endPoint: oss-cn-huhehaote.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tBC11AoCSKPSDqtiyu6 # 访问身份验证中用到用户标识
    accessKeySecret: 3krWVIuBzpECXMTpnqLgRZDH3G7i7S # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: liuzhiqi-oss # oss的存储空间
    dirPrefix: mall/images/ # 上传文件夹路径前缀
    policyExpire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://192.168.3.27:8801/aliyun/oss/callback # 文件上传成功后的回调地址
minio:
  endPoint: http://127.0.0.1:9000 #MinIO服务所在地址（mc config host add XXX服务器名称 http://127.0.0.1:9000 minioadmin minioadmin）
  bucketName: mall-learning-cloud #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
